name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # - name: Decode SSH Private Key
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/private-key.pem
      #     chmod 600 ~/.ssh/private-key.pem

      - name: SSH into EC2 and Run Docker Commands
        run: |
          # SSH into your EC2 instance using the decoded private key
          ssh -i ${{ secrets.PRIVATE_SSH_KEY }} ubuntu@${{secrets.SERVER_PUBLIC_IP}}
          cd Test
          git pull
          sudo docker build -t api-test-ku:latest .
          # Run Docker commands on the EC2 instance
          sudo docker stop api-test-ku || true
          sudo docker rm api-test-ku || true
          sudo docker run -d --name api-test-ku -p 80:80 api-test-ku:latest
          # sudo docker system prune -a
