name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true  # Mask the Docker password
          registry-type: private
          skip-logout: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


      - name: Build Docker image
        run: |
            docker build --builder=default --build-arg MONGO_URL="${{ secrets.MONGO_URL }}" \
                         --build-arg PORT="${{ secrets.PORT }}" --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" \
                         --build-arg JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" --build-arg GOOGLE_OAUTH_CLIENT_ID="${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" \
                         --build-arg GOOGLE_OAUTH_CLIENT_SECRET="${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" \
                         --build-arg NODE_ENV="${{ secrets.NODE_ENV }}" -t reany-website .


      - name: Tag Docker image
        run: docker tag reany-website:latest ${{ secrets.REPO_URL }}/reany-backend-dev:latest

  
      - name: Push Docker image to AWS ECR
        run: docker push ${{ secrets.REPO_URL }}/reany-backend-dev:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          script: |
            sudo docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 89456720648.dkr.ecr.eu-west-2.amazonaws.com
            sudo docker rmi -f 89456720648.dkr.ecr.eu-west-2.amazonaws.com/reany-backend-dev:latest
            sudo docker pull 89456720648.dkr.ecr.eu-west-2.amazonaws.com/reany-backend-dev:latest
            sudo docker stop reany_backend_dev
            sudo docker run --rm --name reany_backend_dev -d -p 8000:8000 89456720648.dkr.ecr.eu-west-2.amazonaws.com/reany-backend-dev:latest
            sudo docker system prune -a --force
