name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true  # Mask the Docker password
          registry-type: private
          skip-logout: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


      - name: Build Docker image
        run: docker build -t wudify-website .


      - name: Tag Docker image
        run: docker tag wudify-website:latest ${{ secrets.REPO_URL }}/wudify-website-dev:latest

  
      - name: Push Docker image to AWS ECR
        run: docker push ${{ secrets.REPO_URL }}/wudify-website-dev:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          script: |
            sudo docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 891377220648.dkr.ecr.eu-west-2.amazonaws.com
            sudo docker rmi -f 891377220648.dkr.ecr.eu-west-2.amazonaws.com/wudify-website-dev:latest
            sudo docker pull 891377220648.dkr.ecr.eu-west-2.amazonaws.com/wudify-website-dev:latest
            sudo docker stop wudify_web
            sudo docker rm wudify_web
            sudo docker run --name wudify_web -d -p 3000:3000 891377220648.dkr.ecr.eu-west-2.amazonaws.com/wudify-website-dev:latest
            sudo docker system prune -a --force
